postgres:
  enabled: true
  replicas: 1
  image:
    repository: postgres
    tag: "15"
  user: demo
  password: demo123
  database: demo

postgresql:
  enabled: false
  auth:
    user: demo
    password: demo123
    database: demo

spring:
  replicas: 2
  image:
    repository: spring-demo-app
    tag: "latest"

service:
  type: NodePort
  port: 8080
  nodePort: 30080

ingress:
  enabled: true
  host: spring-demo.local