apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app
spec:
  replicas: {{ .Values.spring.replicas | default 1 }}
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
        - name: spring-app
          image: "{{ .Values.spring.image.repository }}:{{ .Values.spring.image.tag }}"
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/{{ .Values.postgres.database }}"
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.postgres.user }}
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: postgres-secret
          envFrom:
            - configMapRef:
                name: spring-config
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 5